export const ACTIVE_CONVERSATION_USER = 'ACTIVE_CONVERSATION_USER';
export const CHAT_DATA_SELECTED_USER = 'CHAT_DATA_SELECTED_USER';
export const USER_PROFILE_DISPLAY = 'USER_PROFILE_DISPLAY';

export const SEARCH_USER_DATA_REQ = 'SEARCH_USER_DATA_REQ';
export const SEARCH_USER_DATA = 'SEARCH_USER_DATA';

export const MENU_OPEN = 'MENU_OPEN';
